Document: igc2kmz
Title: Debian igc2kmz Manual
Author: <insert document author here>
Abstract: This manual describes what igc2kmz is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/igc2kmz/igc2kmz.sgml.gz

Format: postscript
Files: /usr/share/doc/igc2kmz/igc2kmz.ps.gz

Format: text
Files: /usr/share/doc/igc2kmz/igc2kmz.text.gz

Format: HTML
Index: /usr/share/doc/igc2kmz/html/index.html
Files: /usr/share/doc/igc2kmz/html/*.html
